name: Looking for an appointment
on:
  push:
    branches:
      - '*'
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          record: ${{ contains(secrets.CYPRESS_RECORD_KEY, '-') }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_FROM_COUNTRY: Israel
          CYPRESS_FM_FROM_UE: No
          CYPRESS_REQUEST_OPTION: "Residence permit for specialists with vocational training (section 18a)"
                                   

          #Form data
          CYPRESS_FIRST_NAME: ${{ secrets.CYPRESS_FIRST_NAME }}
          CYPRESS_LAST_NAME:  ${{ secrets.CYPRESS_LAST_NAME }}
          CYPRESS_BIRTHDAY_DAY:  ${{ secrets.CYPRESS_BIRTHDAY_DAY }}
          CYPRESS_BIRTHDAY_MONTH: ${{ secrets.CYPRESS_BIRTHDAY_MONTH }}
          CYPRESS_BIRTHDAY_YEAR: ${{ secrets.CYPRESS_BIRTHDAY_YEAR }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_NUMBER_OF_APPLICANTS: ${{ secrets.CYPRESS_NUMBER_OF_APPLICANTS }}
          CYPRESS_HAS_RESIDENT_PERMITTED: ${{ secrets.CYPRESS_HAS_RESIDENT_PERMITTED }}
          CYPRESS_RESIDENT_ID: ${{ secrets.CYPRESS_RESIDENT_ID }}

      - name: Screenshots
        uses: actions/upload-artifact@v2
        with:
          path: cypress/screenshots/

      - name: Videos
        uses: actions/upload-artifact@v2
        with:
          path: cypress/videos/

        # If there is a file free-days.png, then it is mean that exist a appointment free, then github will fail and will be send an email!
      - name: Checking if there is an appointment available
        run: if [[ -f cypress/screenshots/language_course_appointment.js/free-days.png ]]; then ls broken_pipeline; fi
